language: node_js
node_js:
  - node
script:
  - npm run test --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
git:
  depth: 4
branches:
  only:
    - "master"
    - "/^v\\d\\.\\d\\.\\d/"
    - "develop"
  # except:
notifications:
  email: false
