
name: npm release

on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org/
    - run: npm ci
    - run: npm run build
    - run: npm run build:dev
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
